### ISSUE TITLE
merge extensions possible collaboration

### ISSUE THREAD

**Issue by ghost** [yomun/auto-ovpn#1]
@yomun 
##
I really like this extension it has alot of potential really good job i was wondering if you would like to merge one of my extensions with this as i think they would integrate well and also would work well together my extension is called [IP finder](https://github.com/LinxGem33/IP-Finder) I’m currently working on my other extension which is called Arc menu let me know if this is something which would interest you.
##

**edit** you can also use my flag icons as your current icons are not rendering correctly (they are oversized) on gnome-shell i haven’t looked at the source code yet so apologies if its something your aware of:+1: 

tested on:
gnome-shell 3.18
ubuntu 16.04

##

kind regards - *LinxGem33*

**Comment by yomun** [comment]
Your suggestion is great. Thanks!
But, this extension just published.
I still want to see whether people likes it or not..
If not, I am lazy to take "big update" actions.

**Comment by yomun** [comment]
Merge works is done.. at least 90%
This few days extensions.gnome.org will be publish new ver 'Auto OVPN'.
Please take a look. Thanks!

**Comment by ghost** [comment]
yeah looks fine ill make a pull request to correct a couple of issues regarding the flags etc.

Pull-request now made #4 

kind regards
