### ISSUE TITLE
Improvement: check for disconnections

### ISSUE THREAD

**Issue by ghost** [yomun/auto-ovpn#2]
As suggested by user "DorianGrey" in the Auto-OVPN webpage's comments:

"Could you add a feature that disconnects your network if the VPN drops and gives a notification? This is sometimes called a killswitch. It keeps data from accidentally being leaked and would make this extension perfect!"

**Comment by yomun** [comment]
Your suggestion will be consider..
Thanks!

**Comment by yomun** [comment]
New design can be close VPN along with WIFI.
This few days extensions.gnome.org will be publish my new 'Auto OVPN'
Please take a look. Thanks!
