### ISSUE TITLE
No connection change after starting Gnome extension in Kali 4.13

### ISSUE THREAD

**Issue by rawkahn** [yomun/auto-ovpn#5]
Hi There - Installed all apt's and Gnome extension (Kali 4.13) but no change in IP/location once extension is started. Do I need to sign up with a VPN service and somehow link it? A bit newer to Linux/Kali, Im used to running VPNs on Windows via VPN service providers - Im sure Im missing something here, sorry for the dummy questions...

![screenshot from 2017-12-25 16-12-19](https://user-images.githubusercontent.com/30449802/34343710-7cf885bc-e98e-11e7-9a2e-10e9b0762740.png)

**Comment by yomun** [comment]
I had check 'auto-ovpn' on Kali Linux.
Besides,
$ sudo apt install openvpn network-manager-openvpn network-manager-openvpn-gnome curl
$ sudo apt install geoip-bin geoip-database geoip-database-extra

'auto-ovpn' still need to use 'bc' command.
Unfortunately, Kali Linux has not install 'bc' program by default..
$ sudo apt install bc

**Comment by rawkahn** [comment]
That did it yomun, thanks! I was missing 'bc'

(Sorry for late reply, busy life sometimes)
