### ISSUE TITLE
freeze system on slow vpn server

### ISSUE THREAD

**Issue by sonvirgo** [yomun/auto-ovpn#6]
I use Ubuntu 17.04 Gnome 3.24
The extension work fine with JP, US server
With filter set to RU (mid night GMT), whole gnome shell freeze

**Comment by yomun** [comment]
That's OpenVPN client site connection issue.
It has not way to know which server is better for your network until you connected..

**Comment by aurovrata** [comment]
Is it possible to switch off pinging for vpn details?  I am able to delay the pinging (max out at 300 sec), but it still freezes the entire desktop.  The extension works well otherwise, just getting rid of the pinging would make it perfect.
